package main

import (
	"fmt"
	"os"

	custody "github.com/aosanya/mwanachama-backend-custody"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: ddl <spec.json> [postgres|sqlite]")
		os.Exit(2)
	}
	dialect := "postgres"
	if len(os.Args) > 2 {
		dialect = os.Args[2]
	}

	s, err := custody.LoadSpec(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Printf("-- generated by cmd/ddl from %s\n", os.Args[1])
	fmt.Printf("-- module %s, domain %s, instance %s -- do not edit by hand\n\n",
		s.Module, s.Domain, s.Instance)
	for _, role := range []string{custody.RoleStructureAct, custody.RoleEvent} {
		if _, ok := s.ByRole(role); ok {
			fmt.Printf("create sequence if not exists custody_%s_seq;\n", role)
		}
	}
	fmt.Println()
	for _, stmt := range s.DDL(dialect) {
		fmt.Println(stmt + ";")
	}
}
